### ISSUE TITLE
Add licence file

### ISSUE THREAD

**Issue by jamiecollinson** [FAO-GSP/GSNmap-TM#1]
Very nice project, and I love the structure including code and sample data.

Could you clarify the licence for the manual and associated code to enable users to adopt? MIT or similar for code and CC-BY 4.0 for manual would be excellent, but I don't know what internal FAO policy dictates.

**Comment by angelini75** [comment]
@yigini, could you answer this issue?

**Comment by yigini** [comment]
the GSNmap datasets and all associated material will be made available under CC BY-NC-SA 3.0 IGO
